load("@rules_cc//cc:defs.bzl", "cc_library")
load("//contrib/bazel:defs.bzl", "GIT_COPTS")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "odb",
    srcs = [
        "source.c",
        "source-files.c",
        "source-inmemory.c",
        "source-loose.c",
        "source-packed.c",
        "streaming.c",
        "transaction.c",
    ],
    hdrs = [
        "source-files.h",
        "source-inmemory.h",
        "source-loose.h",
        "source-packed.h",
        "source.h",
        "streaming.h",
        "transaction.h",
    ],
    copts = GIT_COPTS,
    deps = [
        "//:abspath",
        "//:blob",
        "//:chdir_notify",
        "//:config",
        "//:convert",
        "//:dir",
        "//:environment",
        "//:gettext",
        "//:git_compat_util",
        "//:git_zlib",
        "//:hex",
        "//:list_objects_filter_options",
        "//:lockfile",
        "//:loose",
        "//:mergesort",
        "//:midx",
        "//:object_file",
        "//:object_file_convert",
        "//:oidtree",
        "//:odb",
        "//:pack_bitmap",
        "//:packfile",
        "//:packfile_list",
        "//:path",
        "//:promisor_remote",
        "//:repack",
        "//:replace_object",
        "//:repository",
        "//:run_command",
        "//:strbuf",
        "//:string_list",
        "//:strmap",
        "//:strvec",
        "//:tempfile",
        "//:trace2",
        "//:tree",
        "//:write_or_die",
        "//sha1dc",
        "//sha256",
    ],
)
